name: SpeedHunters
main: src.main.java.com.example.SpeedHunterPlugin
version: "1.0"
api-version: "1.20"
authors: [YourName]
description: Speedrunner vs Hunter minigame plugin
commands:
  sss:
    description: Secret regeneration effect
    permission: speedhunter.secret
  speedrunner:
    description: Become a Speedrunner
  hunter:
    description: Become a Hunter
permissions:
  speedhunter.secret:
    description: Allows use of secret command
    default: op